# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qoe8_XWMt0HCPRLxmDeKs5w1HOroROZW
"""

!pip install pytesseract
!sudo apt install tesseract-ocr
from PIL import Image
import pytesseract
from pix2tex.cli import LatexOCR

def image_to_latex(image_path):
    # Load the image
    img = Image.open(image_path)

    # Initialize the LaTeX OCR model for extracting formulas
    latex_model = LatexOCR()

    # Extract LaTeX formula from the image
    # Assuming the image contains formula in a single block
    try:
        latex_formula = latex_model(img)
    except Exception as e:
        print(f"An error occurred while extracting formulas: {e}")
        latex_formula = ""

    # Use Tesseract OCR to extract regular text from the image
    try:
        text = pytesseract.image_to_string(img, config='--psm 6')
    except Exception as e:
        print(f"An error occurred while extracting text: {e}")
        text = ""

    # Combine the outputs, prioritize manual checking and corrections
    combined_output = f"Extracted Text:\n{text}\n\nExtracted Formula:\n{latex_formula}"

    return combined_output


image_path = '/content/full derivationwith text.png'
latex_content = image_to_latex(image_path)
print(latex_content)